// Generated by dts-bundle-generator v9.5.1

import React$1 from "react";

export declare let store: Storage;
export type ArrayElement<ArrayType extends unknown[]> =
  ArrayType extends (infer ElementType)[] ? ElementType : never;
export interface ArraySetter<Value extends unknown[]> {
  (newValue: Value | ((prev: Value) => Value)): void;
  fill: (value: any, start?: number, end?: number) => Value;
  pop: () => Value;
  push: (...items: Value) => Value;
  reverse: () => Value;
  shift: () => Value;
  sort: (compareFn?: (a: any, b: any) => number) => Value;
  splice: (start: number, deleteCount?: number, ...items: Value) => Value;
  unshift: (...items: Value) => Value;
  append: (...items: Value) => Value;
  prepend: (...items: Value) => Value;
  concat: (...items: Value) => Value;
  slice: (start?: number, end?: number) => Value;
  filter: (fn: (value: any, index: number, array: Value) => any) => Value;
  map: (
    fn: (value: any, index: number, array: Value) => ArrayElement<Value>,
  ) => Value;
  reduce: (
    fn: (
      previous: Value,
      current: ArrayElement<Value>,
      index: number,
      array: Value,
    ) => Value,
    initial: Value,
  ) => Value;
  reduceRight: (
    fn: (
      previous: Value,
      current: ArrayElement<Value>,
      index: number,
      array: Value,
    ) => Value,
    initial: Value,
  ) => Value;
  remove: (index: number) => Value;
}
export interface NumberSetter<Value> {
  (newValue: Value | ((prev: Value) => Value)): void;
  add: (value: number) => Value;
  substract: (value: number) => Value;
}
export interface ObjectSetter<Value> {
  (newValue: Value | ((prev: Value) => Value)): void;
  remove: (key: string) => Value;
  assign: (extra: object) => Value;
  extend: (extra: object) => Value;
}
export interface UnknownSetter<Value> {
  (newValue: Value | ((prev: Value) => Value)): void;
  [key: string]: (...args: any[]) => Value;
}
export type Setter<Value> = Value extends any[]
  ? ArraySetter<Value>
  : Value extends Number
    ? NumberSetter<Value>
    : Value extends Object
      ? ObjectSetter<Value>
      : UnknownSetter<Value>;
export type Selector<Value> = string | ((state: any) => Value);
export interface StoreContextType {
  state: React$1.MutableRefObject<any>;
  setState: (updated: any) => void;
  subscribe: (fn: (old: any) => void) => () => void;
}
export declare const Context: React$1.Context<StoreContextType>;
export declare const useSelector: <Value = any>(sel?: Selector<Value>) => Value;
export declare const useActions: <Value = any>(
  sel?: Selector<Value>,
) => Setter<Value>;
export declare const useStore: <Value = any>(
  sel?: string,
) => [Value, Setter<Value>];
export interface StoreProps {
  children?: React$1.ReactNode;
  [key: string]: unknown;
}
declare const _default: ({
  children,
  ...initial
}: StoreProps) => import("react/jsx-runtime").JSX.Element;

export { _default as default };

export {};
